Update qvm-create-windows-qube

diff --git a/qvm-create-windows-qube b/qvm-create-windows-qube
--- a/qvm-create-windows-qube
+++ b/qvm-create-windows-qube
@@ -8,6 +8,15 @@ BLUE='\033[0;34m'
 GREEN='\033[0;32m'
 NC='\033[0m'
 
+# Qubes version impacts rpc policy later in the script
+qubes_version=$(awk -F"[()]" '{print $2}' /etc/qubes-release)
+if [ ${qubes_version} = "R4.0" ] ||  [ ${qubes_version} = "R4.1" ] ; then
+    echo -e "${BLUE}[i]${NC} Qubes version ${qubes_version} is supported." >&2
+else
+    echo -e "${RED}[!]${NC} Qubes version ${qubes_version} not supported or missing. Exiting..." >&2
+    exit 1
+fi
+
 error() {
     exit_code="$?"
     echo -e "${RED}[!]${NC} An unexpected error has occurred! Exiting..." >&2
@@ -343,9 +352,22 @@ for (( counter = 1; counter <= count; counter++ )); do
     # Post QWT scripts
 
     # Prepend allowing policy to qubes.Filecopy and copy post scripts from resources qube to Windows
-    policy="$resources_qube $qube allow"
-    policy_file="/etc/qubes-rpc/policy/qubes.Filecopy"
-    sed -i "1i$policy" "$policy_file"
+    if [ "${qubes_version}"="R4.0" ] ; then
+        policy="$resources_qube $qube allow"
+        policy_file="/etc/qubes-rpc/policy/qubes.Filecopy"
+        sed -i "1i$policy" "$policy_file"
+    else
+        #tmp_file is used to work around permissions complexities in target directory without having to resort to double quoting inside "sudo sh -c '...'"
+        tmp_file="/tmp/qvm-create-windows-vm-$$"
+        
+        policy="qubes.Filecopy          *          $resources_qube $qube allow"
+        echo "# Temporary policy for qvm-create-windows-qube invocation with PID=$$, can be deleted." > ${tmp_file}
+        echo "${policy}" >> ${tmp_file}
+        
+        policy_file="/etc/qubes/policy.d/25-qvm-create-windows-qube-bash-$$.policy"
+        sudo mv "${temp_file}" "${policy_file}"
+    fi
+    
     qvm-run -q "$resources_qube" "cd '$resources_dir' && qvm-copy-to-vm $qube post"
 
     post_incoming_dir="%USERPROFILE%\\Documents\\QubesIncoming\\$resources_qube\\post"
@@ -389,8 +411,14 @@ for (( counter = 1; counter <= count; counter++ )); do
 
     # Clean up post scripts and remove policy
     qvm-run -q "$qube" "rmdir /s /q $post_incoming_dir\\..\\.." || true
-    sed -i "/^$policy$/d" "$policy_file"
-
+    
+    if [ "${qubes_version}"="R4.0" ] ; then
+        #unmodify R4.0 policy file
+        sed -i "/^$policy$/d" "$policy_file"
+    else
+        #remove custom R4.1 policy file
+        sudo rm -f "${policy_file}"
+    fi
     echo -e "${BLUE}[i]${NC} Shutting down Windows..." >&2
     # Shutdown and wait until complete before finishing or starting next installation
     if qvm-run -q "$qube" "shutdown /s /t 0"; then
